server:
  port: 8890
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true
        secure: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dongbborigin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: Root
    password: Root$123
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  security:
    loginType: JSON
    # 配置 security 登录页面的用户名和密码
    user:
      name: admin
      password: admin


logging:
  config: classpath:logback-spring.xml
  #level:
    # 跟日志记录器是 info级别
    #    root: info
    #com.tusdao.mapper.base: DEBUG
    #io.swagger.models.parameters.AbstractSerializableParameter: error

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true