server:
  port: 8893
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true  # 如果为true，则浏览器脚本将无法访问cookie
        secure: false # 如果为true，则仅通过HTTPS连接发送cookie，HTTP无法携带cookie。

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/devicedb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Root$123
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  security:
    loginType: JSON
    user:
      name: admin
      password: admin

jwt:
  secret: ffjaksdfjaklf # 秘钥
  expiration: 3600000   # 过期时间 (秒)
  header: JWTHeaderName # 请求头信息

logging:
  config: classpath:logback-spring.xml

mybatis:
    configuration:
      mapUnderscoreToCamelCase: true

